version: '3.7'

services:
  db:
    container_name: postgres
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - stream-sphere

volumes:
  postgres_data:

networks: 
  stream-sphere:
